server:
  port: 4560

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.reform.et.controllers

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/et-hearings-api/,optional:configtree:/mnt/secrets/et/"
  application:
    name: ET Hearings API
  main:
    allow-bean-definition-overriding: true
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}${DB_OPTIONS:}
#    username: ${DB_USER_NAME}
#    password: ${DB_PASSWORD}
#    properties:
#      charSet: UTF-8
#    hikari:
#      minimumIdle: 2
#      maximumPoolSize: 10
#      idleTimeout: 10000
#      poolName: {to-be-defined}HikariCP
#      maxLifetime: 7200000
#      connectionTimeout: 30000
#  jpa:
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            # silence the 'wall-of-text' - unnecessary exception throw about blob types
#            non_contextual_creation: true

azure:
  application-insights:
    instrumentation-key: ${AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
  service-bus:
    amqp-connection-string-template: ${AMQP_CONNECTION_STRING:amqps://%1s?amqp.idleTimeout=%2d}
    connection-postfix: ${HMC_HEARINGS_TOPIC_CONNECTION_POSTFIX:.servicebus.windows.net}
    hmc-to-hearings-api:
      namespace: ${HMC_HEARINGS_TOPIC_NAMESPACE:}
      topicName: ${HMC_HEARINGS_TOPIC_NAME:}
      subscriptionName: ${HMC_HEARINGS_TOPIC_SUBSCRIPTION_NAME:}
      receiveTimeout: ${HMC_HEARINGS_TOPIC_RECEIVE_TIMEOUT:1}
      idleTimeout: ${HMC_HEARINGS_TOPIC_IDLE_TIMEOUT:3600000}
      username: ${HMC_HEARINGS_TOPIC_POLICY_NAME:}
      password: ${HMC_HEARINGS_TOPIC_ACCESS_KEY:}

idam:
  api:
    url: ${IDAM_API_BASEURL:http://localhost:5000}
    jwksUrl: ${IDAM_JWKS_BASEURL:http://localhost:5000/o/jwks}
  s2s-auth:
    url: ${SERVICE_AUTH_PROVIDER_URL:http://localhost:4502}
    secret: ${ET_HEARINGS_S2S_SECRET:AAAAAAAAAAAAAAAA}
    microservice: ${MICRO_SERVICE:et_hearings_api}
 # s2s-authorised:
  #  services: ${IDAM_S2S_AUTH_MICROSERVICES:xui_webapp} todo: request onboarding with xui_webapp

core_case_data:
  api:
    url: ${CASE_DATA_STORE_BASEURL:http://localhost:4452}
  search:
    page_size: ${CCD_SEARCH_PAGE_SIZE:100}

et:
  hmctsServiceId: ${HMCTS_SERVICE_ID:BHA1}

etcos:
  system:
    username: et.service@hmcts.net
    password: Pa55word11

  flags:
    hmc-to-hearings-api:
      enabled: ${HMC_HEARINGS_LISTENING_ENABLED:false}
    tribunals-to-hearings-api:
      enabled: ${TRIBUNALS_HEARINGS_LISTENING_ENABLED:false}

hmc:
  url: ${HMC_URL:http://localhost:8080}
