java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    et:
      secrets:
        - name: app-insights-connection-string
          alias: app-insights-connection-string
