java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
  #  et-hearings-api:
  #    secrets:
  #      - name: et-hearings-api-s2s-secret
  #        alias: ET_HEARINGS_S2S_SECRET
    et:
      secrets:
        - AppInsightsInstrumentationKey
